# Name - Kulkarni Omkar Vikas

## Project-1 : IRIS Flower Classification 

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
from sklearn.datasets import load_iris

In [3]:
iris_data=load_iris()

In [4]:
dir(iris_data)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
iris_data.data[:6]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [6]:
len(iris_data.target)

150

In [7]:
len(iris_data.data)

150

In [8]:
Sepal_Length=iris_data.data[:,0]
len(Sepal_Length)

150

In [9]:
Sepal_Width =iris_data.data[:,1]
len(Sepal_Width)

150

In [10]:
Petal_Length =iris_data.data[:,2]
len(Petal_Length)

150

In [11]:
Petal_Width=iris_data.data[:,3]
len(Petal_Width)

150

In [12]:
type(Sepal_Length)

numpy.ndarray

In [15]:
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(iris_data.data,iris_data.target,test_size=0.2)

In [19]:
reg_model=LogisticRegression()

In [20]:
reg_model.fit(x_train,y_train)

LogisticRegression()

In [21]:
reg_model.predict(x_test)

array([1, 1, 1, 0, 0, 0, 0, 0, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 2, 0, 0, 1,
       2, 2, 0, 0, 1, 2, 1, 2])

In [22]:
y_test

array([1, 1, 1, 0, 0, 0, 0, 0, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 0, 0, 1,
       2, 2, 0, 0, 1, 2, 1, 2])

In [24]:
reg_model.score(x_test,y_test)

0.9666666666666667